server {
    listen 80;
    server_name custom-element-proxy;

    location = / {
        root /usr/share/nginx/html;
        try_files /index.html = 500;
    }

    location / {
        proxy_pass http://my-element;
    }

    location /api/ {
        proxy_pass http://api:3000;
        rewrite ^/api/(.*) /$1 break; 
    }

}
